# Generated by Django 4.2.10 on 2024-02-12 06:25

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="Img",
            field=models.ImageField(
                default="profile_images/default.jpg",
                upload_to=users.models.profile_image_path,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_no",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 10 digits long.", regex="\\d{10}"
                    )
                ],
            ),
        ),
    ]
