# Generated by Django 4.2.10 on 2024-02-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_img_alter_profile_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["is_superuser"]},
        ),
    ]
