# Generated by Django 4.2.10 on 2024-02-13 10:10

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="Img",
            field=models.ImageField(
                default="profile_images/default.jpg",
                upload_to=users.models.profile_image_path,
                verbose_name="Image",
            ),
        ),
    ]
