# Generated by Django 4.2.10 on 2024-02-13 10:07

from django.db import migrations, models
import packages.models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="places",
            name="Img",
            field=models.ImageField(
                default="profile_images/default.jpg",
                upload_to=packages.models.profile_image_path,
                verbose_name="Image",
            ),
        ),
    ]
