# Generated by Django 4.2.10 on 2024-02-11 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_Packages",
            fields=[
                ("deal_id", models.AutoField(primary_key=True, serialize=False)),
                ("no_of_persons", models.IntegerField()),
                ("total_cost", models.IntegerField(default=0)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
