# Generated by Django 4.2.10 on 2024-02-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("TripRecords", "0001_initial"),
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_packages",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals_packages",
                to="packages.packages",
            ),
        ),
    ]
