# Generated by Django 4.2.10 on 2024-02-12 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("TripRecords", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_packages",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user_packages",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
